# Generated by Django 5.1.5 on 2025-02-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bst.club'),
        ),
        migrations.AddField(
            model_name='member',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bst.project'),
        ),
    ]
