# Generated by Django 5.1.5 on 2025-02-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], default='Admin', max_length=15),
        ),
    ]
