# Generated by Django 5.1.5 on 2025-04-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('bst', '0004_remove_award_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='awards',
            field=models.ManyToManyField(related_name='members', to='bst.award'),
        ),
    ]
