# Generated by Django 5.1.5 on 2025-04-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_member_awards'),
        ('bst', '0005_meeting_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='awards',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='bst.award'),
        ),
    ]
