# Generated by Django 5.1.5 on 2025-04-26 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_member_awards'),
        ('bst', '0012_remove_eventphoto_url_eventphoto_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRemovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bst.club')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_to_remove', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_who_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
