# Generated by Django 5.1.5 on 2025-02-02 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_phone_number_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='DOB',
            new_name='dob',
        ),
    ]
