# Generated by Django 5.1.5 on 2025-04-26 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_memberremovalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberremovalrequest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_to_remove', to='accounts.member'),
        ),
        migrations.AlterField(
            model_name='memberremovalrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_who_requested', to='accounts.admin'),
        ),
    ]
