# Generated by Django 5.1.5 on 2025-02-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_dob_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(default='Member', editable=False, max_length=20),
        ),
    ]
