# Generated by Django 5.1.5 on 2025-04-26 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_memberremovalrequest_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberremovalrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='memberremovalrequest',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_requests', to='accounts.member'),
        ),
        migrations.AlterField(
            model_name='memberremovalrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_requests_created', to='accounts.admin'),
        ),
        migrations.AlterField(
            model_name='memberremovalrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
