# Generated by Django 5.1.5 on 2025-02-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_user_id_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='assinged_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
