# Generated by Django 5.1.5 on 2025-04-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_memberremovalrequest_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberremovalrequest',
            name='club',
        ),
    ]
