# Generated by Django 5.1.5 on 2025-03-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='price',
            new_name='fee',
        ),
        migrations.RenameField(
            model_name='eventregistration',
            old_name='price',
            new_name='fee',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='price',
            new_name='fee',
        ),
    ]
