# Generated by Django 5.1.5 on 2025-02-28 13:26

import bst.models.club
import bst.models.meeting
import bst.models.membership
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.CharField(default=bst.models.club.get_alphanumeric_id, editable=False, max_length=5, primary_key=True, serialize=False)),
                ('club_name', models.CharField(default='Bharat Storytellers', max_length=255)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.CharField(default=bst.models.membership.get_alphanumeric_id, editable=False, max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration_in_months', models.IntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('location', models.TextField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bst.club')),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('registration_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=6)),
                ('occupation', models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employeed'), ('Business', 'Business'), ('Self Employeed', 'Self Employeed')], default='Student', max_length=20)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_model', to='bst.event')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.CharField(default=bst.models.meeting.get_alphanumeric_id, editable=False, max_length=5, primary_key=True, serialize=False)),
                ('agenda', models.CharField(blank=True, null=True)),
                ('schedule', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('CE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ce_meetings', to='accounts.member')),
                ('MOC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moc_meetings', to='accounts.member')),
                ('OMC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omc_meetings', to='accounts.member')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bst.club')),
            ],
        ),
    ]
