# Generated by Django 5.1.5 on 2025-02-27 10:19

import bst.models.membership
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='id',
            field=models.CharField(default=bst.models.membership.get_alphanumeric_id, editable=False, max_length=4, primary_key=True, serialize=False),
        ),
    ]
