# Generated by Django 5.1.5 on 2025-02-27 12:36

import bst.models.club
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_id',
            field=models.CharField(default=bst.models.club.get_alphanumeric_id, editable=False, max_length=4, primary_key=True, serialize=False),
        ),
    ]
