# Generated by Django 5.1.5 on 2025-04-18 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('eligible_age', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_club_size', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='initiative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bst.initiative'),
        ),
    ]
