# Generated by Django 5.1.5 on 2025-04-18 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0002_initiative_club_initiative'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bst.membership'),
        ),
    ]
