# Generated by Django 5.1.5 on 2025-02-27 16:50

import bst.models.meeting
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0002_alter_club_club_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default=bst.models.meeting.get_alphanumeric_id, editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
