# Generated by Django 5.1.5 on 2025-02-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0002_alter_club_club_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(default=454, editable=False, max_length=3, primary_key=True, serialize=False),
        ),
    ]
