# Generated by Django 5.1.5 on 2025-02-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0003_alter_meeting_meeting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
