# Generated by Django 5.1.5 on 2025-04-18 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0003_initiative_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='members',
        ),
    ]
