# Generated by Django 5.1.5 on 2025-03-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0004_alter_eventregistration_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='landmark',
        ),
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='club_images/'),
        ),
        migrations.AddField(
            model_name='club',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
