# Generated by Django 5.1.5 on 2025-04-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0004_remove_award_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
