# Generated by Django 5.1.5 on 2025-04-22 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_member_awards'),
        ('bst', '0005_meeting_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='CE',
        ),
        migrations.AddField(
            model_name='meeting',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinator_meetings', to='accounts.member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='filler_counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filler_counter_meetings', to='accounts.member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='listener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listener_meetings', to='accounts.member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_meetings', to='accounts.member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='president',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president_meetings', to='accounts.member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_meetings', to='accounts.member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='sergeant_at_arms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saa_meetings', to='accounts.member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='speaker1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker1_meetings', to='accounts.member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='speaker2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker2_meetings', to='accounts.member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='speaker3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker3_meetings', to='accounts.member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='speech_evaluator1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speech_evaluator1_meetings', to='accounts.member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='speech_evaluator2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speech_evaluator2_meetings', to='accounts.member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='timekeeper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timekeeper_meetings', to='accounts.member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='vice_president_education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpe_meetings', to='accounts.member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='vice_president_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vpm_meetings', to='accounts.member'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='vice_president_public_relations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vppr_meetings', to='accounts.member'),
        ),
    ]
