# Generated by Django 5.1.5 on 2025-04-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0007_remove_event_fee_event_attendees_event_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='formatted_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='eventphoto',
            name='event',
        ),
        migrations.RemoveField(
            model_name='scheduleitem',
            name='event',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='photos',
            field=models.ManyToManyField(blank=True, to='bst.eventphoto'),
        ),
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.ManyToManyField(blank=True, to='bst.scheduleitem'),
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, to='bst.speaker'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
