# Generated by Django 5.1.5 on 2025-04-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0008_remove_event_formatted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.JSONField(default=None),
        ),
    ]
