# Generated by Django 5.1.5 on 2025-04-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0010_remove_event_speakers_event_speakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='event',
            name='speakers',
        ),
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, to='bst.speaker'),
        ),
    ]
