# Generated by Django 5.1.5 on 2025-04-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0011_alter_event_categories_remove_event_speakers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventphoto',
            name='url',
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_photos/'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='speaker_images/'),
        ),
    ]
