# Generated by Django 5.1.5 on 2025-04-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0012_remove_eventphoto_url_eventphoto_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='dms_position',
        ),
        migrations.RemoveField(
            model_name='club',
            name='position',
        ),
        migrations.AddField(
            model_name='club',
            name='map',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='meeting_time',
            field=models.CharField(blank=True, default='Tuesdays, 6:30 PM', max_length=100, null=True),
        ),
    ]
