# Generated by Django 5.1.5 on 2025-04-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0013_remove_club_dms_position_remove_club_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='meeting_time',
            field=models.CharField(default='Tuesdays, 6:30 PM', max_length=100),
        ),
    ]
