# Generated by Django 5.1.5 on 2025-04-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0014_alter_club_meeting_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='eligible_age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
