# Generated by Django 5.1.5 on 2025-05-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_memberremovalrequest_club'),
        ('bst', '0015_alter_initiative_eligible_age_alter_initiative_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectHistory',
            new_name='ProjectAssignment',
        ),
    ]
