# Generated by Django 5.1.5 on 2025-05-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0016_rename_projecthistory_projectassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('Weekly', 'Weekly'), ('Executive Committee', 'Executive Committee')], default='Weekly', max_length=50),
        ),
    ]
