# Generated by Django 5.1.5 on 2025-05-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0017_meeting_meeting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_price',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
