# Generated by Django 5.1.5 on 2025-05-07 10:35

import bst.models.event_registration
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0018_alter_event_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='reg_id',
            field=models.CharField(default=bst.models.event_registration.get_alphanumeric_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
