# Generated by Django 5.1.5 on 2025-05-07 10:44

import bst.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0019_alter_eventregistration_reg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(default=bst.models.event.get_alphanumeric_id, editable=False, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
