# Generated by Django 5.1.5 on 2025-05-09 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_memberremovalrequest_club'),
        ('bst', '0020_alter_event_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executivecommittee',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='executivecommittee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='executivecommittee',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='executivecommittee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='executivecommittee',
            name='role',
        ),
        migrations.AddField(
            model_name='executivecommittee',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.member'),
        ),
        migrations.AlterField(
            model_name='executivecommittee',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bst.club'),
        ),
    ]
