# Generated by Django 5.1.5 on 2025-05-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0021_remove_executivecommittee_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivecommittee',
            name='role',
            field=models.CharField(choices=[('president', 'President'), ('vice_president_education', 'Vice President - Education'), ('vice_president_membership', 'Vice President - Membership'), ('vice_president_public_relations', 'Vice President - Public Relations'), ('secretary', 'Secretary'), ('sergeant_at_arms', 'Sergeant at Arms')], default='president', max_length=50),
        ),
    ]
