# Generated by Django 5.1.5 on 2025-05-09 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0022_executivecommittee_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='executivecommittee',
            unique_together={('club', 'role')},
        ),
    ]
