# Generated by Django 5.1.5 on 2025-05-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0023_alter_executivecommittee_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='executivecommittee',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='executivecommittee',
            name='role',
            field=models.CharField(choices=[('President', 'President'), ('Vice President - Education', 'Vice President - Education'), ('Vice President - Membership', 'Vice President - Membership'), ('Vice President - Public Relations', 'Vice President - Public Relations'), ('Secretary', 'Secretary'), ('Sergeant at Arms', 'Sergeant at Arms')], default='President', max_length=50),
        ),
        migrations.RemoveField(
            model_name='executivecommittee',
            name='club',
        ),
    ]
