# Generated by Django 5.1.5 on 2025-05-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bst', '0024_alter_executivecommittee_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='map',
            field=models.TextField(blank=True, null=True),
        ),
    ]
