import { Roboto } from 'next/font/google'
import { MainNav } from "@/components/ui/NavBar";
import "./globals.css";
 
const roboto = Roboto({
  weight: ['400', '300', '100', '500', '900', '700'],
  subsets: ['latin'],

})
export const metadata = {
  title: "Bhartat Story",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased bg-[#FAF9F9] `}>
        <MainNav />
        {children}
      </body>
    </html>
  );
}
