import { Poppins } from "next/font/google";
import "./globals.css";
import { MainNav } from "@/components/ui/NavBar";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // Adjust weights as needed
});

export const metadata = {
  title: "Bhartat Story",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased bg-[#FAF9F9]`}>
        <MainNav />
        {children}
      </body>
    </html>
  );
}
