# Generated by Django 5.1.5 on 2025-03-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_admin_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='assinged_date',
            new_name='assigned_date',
        ),
        migrations.AlterField(
            model_name='member',
            name='occupation',
            field=models.CharField(choices=[('Student', 'Student'), ('Employee', 'Employee'), ('Business', 'Business'), ('Self Employed', 'Self Employed')], default='Student', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(default='Member', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
    ]
