import "./globals.css";

export const metadata = {
  title: "Bhartat Story",
  description: "Generated by create next app",
};

// TODO: fetch data of the user from the API and based on that decide to show member dashboard or admin dashboard

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased bg-[#FAF9F9] `}>
        {children}
      </body>
    </html>
  );
}
